"""Shared defaults and display settings for MOSAIC."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DISPLAY_LEVELS = (0, 255)
ROI_SIZE = (80, 80)
BACKGROUND_ROI_SIZE = (120, 120)
RECOMMENDED_BACKGROUND_RADIUS = 10
BACKGROUND_RECOMMEND_CANDIDATES = 100
BACKGROUND_RECOMMEND_DURATION_S = 10.0
AUTO_ROI_DURATION_S = 3.0
AUTO_ROI_MAX_FRAMES = 300
AUTO_ROI_CHANGE_PERCENTILE = 90
AUTO_ROI_MIN_PIXELS = 12
GRAPH_BACKGROUND = "#4A4A4A"
GRAPH_FOREGROUND = "#FFFFFF"
GRAPH_GRID_ALPHA = 0.22
SIGNAL_TRACE_RAW_COLOR = "#FFFFFF"
SIGNAL_TRACE_CORRECTED_COLOR = "#FFD23F"
MS_PER_SECOND = 1000.0
TRANSIENT_DEFAULT_PRE_START_S = 0.05
TRANSIENT_DEFAULT_PACING_INTERVAL_S = 0.50
TRANSIENT_DEFAULT_SMOOTH_S = 0.02
TRANSIENT_DEFAULT_PROMINENCE_NOISE = 3.0
TRANSIENT_DEFAULT_START_FRACTION = 0.1
TRANSIENT_RECOVERY_FRACTION = 0.25
TRANSIENT_RECOVERY_HOLD_S = 0.03
TRANSIENT_TAIL_TURN_FRACTION = 0.60
TRANSIENT_SECONDARY_RISE_FRACTION = 0.08
TRANSIENT_SECONDARY_LOOKAHEAD_S = 0.15
TRANSIENT_DEFAULT_DECAY_PERCENT_VALUES = (10, 50, 90)
SR_CALCIUM_DEFAULT_PRE_START_S = 2.0
SR_CALCIUM_DEFAULT_POST_START_S = 10.0
SR_CALCIUM_DEFAULT_FIT_START_S = 0.0
SR_CALCIUM_DEFAULT_FIT_END_S = 10.0
SR_CALCIUM_DETECTION_SMOOTH_S = 0.20
PHOTOBLEACH_EVENT_PRE_PADDING_S = 0.05
PHOTOBLEACH_EVENT_POST_PADDING_S = 0.20
PHOTOBLEACH_MIN_BASELINE_FRACTION = 0.10
PHOTOBLEACH_MIN_BASELINE_POINTS = 10
PHOTOBLEACH_DEFAULT_ROBUSTNESS_SCALE = 1.0
PHOTOBLEACH_DEFAULT_FIT_START_S = 0.0
PHOTOBLEACH_DEFAULT_FIT_END_S = 20.0
ROI_COLORS = [
    "#FFD23F",
    "#FF6B6B",
    "#7CFF6B",
    "#B56BFF",
    "#FF9F43",
    "#4DFFDB",
]


